name: Bug report
description: File a bug/defect report
title: 'fix: <short description>'
labels: ['bug']
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!

    - type: markdown
      attributes:
          value: |
              ### Description

    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: A clear and concise description of the bug.
          placeholder: Briefly describe the issue
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              ### Severity & Impact

    - type: dropdown
      id: severity
      attributes:
          label: Severity
          options:
              - blocker (outage/data-loss)
              - critical (major functionality broken)
              - minor (workaround exists)
              - trivial
      validations:
          required: true

    - type: input
      id: impact
      attributes:
          label: Impact
          placeholder: Who/what is affected? (e.g., login blocked for all users)

    - type: dropdown
      id: reproducibility
      attributes:
          label: Reproducibility
          options:
              - always
              - often
              - rarely
              - once

    - type: dropdown
      id: area
      attributes:
          label: Affected area
          multiple: true
          options:
              - API
              - Auth
              - RabbitMQ
              - Redis
              - Config/Env
              - Docker/Infra
              - CI/CD
              - Docs
              - Other

    - type: markdown
      attributes:
          value: |
              ### Reproduction

    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
          description: Provide exact steps to reproduce the issue.
          placeholder: |
              1. Go to ...
              2. Run ...
              3. Observe ...
      validations:
          required: true

    - type: input
      id: expected
      attributes:
          label: Expected behavior
          placeholder: What should have happened?
      validations:
          required: true

    - type: input
      id: actual
      attributes:
          label: Actual behavior
          placeholder: What actually happened?
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              ### Environment

    - type: textarea
      id: environment
      attributes:
          label: Environment
          placeholder: |
              OS/macOS version:
              Node version:
              Docker: on/off (version)
              Service mode: dev/stage/prod

    - type: input
      id: version
      attributes:
          label: Version/Commit
          placeholder: e.g., v1.2.3 or commit hash

    - type: markdown
      attributes:
          value: |
              ### Evidence

    - type: textarea
      id: logs
      attributes:
          label: Relevant logs/output
          description: Paste any relevant logs. Use backticks to format.
          render: shell

    - type: markdown
      attributes:
          value: |
              ### Regression & Workaround

    - type: checkboxes
      id: regression
      attributes:
          label: Regression
          options:
              - label: This worked in a previous version

    - type: textarea
      id: workaround
      attributes:
          label: Known workaround (if any)
          placeholder: Describe any temporary workaround

    - type: markdown
      attributes:
          value: |
              ### Related

    - type: input
      id: links
      attributes:
          label: Related links
          placeholder: PRs, commits, issue IDs, dashboards

    - type: markdown
      attributes:
          value: |
              ### Final checks

    - type: checkboxes
      id: checks
      attributes:
          label: Checks
          options:
              - label: I searched existing issues
                required: true
              - label: I can reproduce this consistently
              - label: I can provide a minimal reproduction
